### ISSUE TITLE
Calling operator "bpy.ops.export_mesh.stl" error, could not be found

### ISSUE THREAD

**Issue by jdalearn** [IronicMollusk/xwing-dial-generator#1]
![image](https://github.com/user-attachments/assets/a1974f2b-4c29-43f4-a905-02f88b1c1d50)
I get that error each time I run the script.

**Comment by jdalearn** [comment]
I believe this fixes it, change line 186 of the .blend file to be

bpy.ops.wm.stl_export(filepath=output_path)

Source of info: https://developer.blender.org/docs/release_notes/4.1/pipeline_assets_io/

**Comment by LexarDevelopment** [comment]
thanks for the feedback and research. can i ask what version of blender you're using? I cant reproduce the issue in v4.0

**Comment by IronicMollusk** [comment]
thanks for the feedback and research. <s>can i ask what version of blender you're using?</s> I cant reproduce the issue in v4.0.2.

edit: neverminded, I see it in the screenshot you're using 4.2. let me see if I can reproduce on that version, as its the LTS version and preferred.
